apiVersion: v1
kind: Secret
metadata:
  name: quay-io-credentials
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkR2xzYkhWekszRjFZWGxmYVc5ZlkzSmxaR1Z1ZEdsaGJITTZNVFEzTmxaVlRsWlhNRmcyTTFKYVNFOUZOelkyV0VaUU5USkpPVEJPTVZoVVdWTTBURkpMTmtkVFRWZEdPRWxZV1VVeFZUVTNWRE5FVEVKWFJUZ3hNZz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
